## Basic Usage of NumPy

In [20]:
import numpy as np

In [21]:
arr = np.array([[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]]], dtype=np.int32)

In [22]:
print(arr)

[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]


In [23]:
arr.dtype

dtype('int32')

ndim indicates the number of dimensions

In [24]:
arr.ndim

3

shape indicates the size of each dimension

In [16]:
arr.shape

(2, 3, 2)

multiply each value in the ndarray by 10

In [25]:
arr * 10

array([[[10, 10],
        [20, 20],
        [30, 30]],

       [[40, 40],
        [50, 50],
        [60, 60]]], dtype=int32)

In [26]:
ones_arr = np.ones((10, 2))

In [27]:
ones_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
ones_arr.ndim

2

## More NumPy arrays

In [18]:
np.array([1, 2, 3])

array([1, 2, 3])

In [19]:
np.array([1, "b", 3])

array(['1', 'b', '3'], dtype='<U21')